timer:
  min: 1  # SECONDS
  max: 10 # SECONDS
  # (SIDE NOTE: Number is multiplied by 20 to convert to game ticks)
inital_random:
  radius: 10
  times: 10
random:
  radius: 100
world: "void"
only_replace_air: true
messages:
  spawned: "&aA ${SPAWNED_BLOCK} has spawned at ${X} ${Y} ${Z}"
  chest_spawn: "&aA chest has spawned!"
  error: "&cI uh... what broke?"